# Generated by Django 6.1.1 on 2026-09-25 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('governorate', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('estimated_delivery', models.CharField(default='1–3 Days', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'toomakt_shipping_rates',
                'ordering': ['governorate'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('governorate', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('products_interested', models.TextField(blank=True, default='')),
                ('requested_quantity', models.PositiveIntegerField(default=100)),
                ('monthly_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=30)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'toomakt_wholesale_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='apartment_floor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='building_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='governorate',
            field=models.CharField(default='Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pieces_per_pack_snapshot',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces_per_pack',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='Egypt', max_length=100),
        ),
    ]
