# Generated by Django 6.1.1 on 2026-09-28 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingrate_wholesalerequest_order_apartment_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('related_order_number', models.CharField(blank=True, default='', max_length=100)),
                ('related_product_id', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'toomakt_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reviewed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount (%)'), ('fixed', 'Fixed Amount Discount (EGP)')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('instapay', 'InstaPay / Bank Transfer'), ('cod', 'Cash On Delivery'), ('card', 'Credit / Debit Card (Online)'), ('bank', 'Direct Bank Wire'), ('apple_pay', 'Apple Pay / Digital Wallet')], default='instapay', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('waiting_verification', 'Waiting Payment Verification'), ('authorized', 'Authorized'), ('paid', 'Paid in Full'), ('rejected', 'Payment Rejected'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('waiting_for_payment', 'Waiting for Payment'), ('payment_review', 'Payment Review'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('preparing', 'Preparing Order'), ('processing', 'Processing in Atelier'), ('packed', 'Packed in Insulated Cooler'), ('shipped', 'Shipped via Express'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_rejected', 'Payment Rejected'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(default='instapay', max_length=30)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_reference', models.CharField(blank=True, default='', max_length=150)),
                ('payment_screenshot', models.TextField(blank=True, default='')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='waiting_verification', max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('admin_reviewer', models.CharField(blank=True, default='', max_length=150)),
                ('admin_review_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmations', to='store.order')),
            ],
            options={
                'db_table': 'toomakt_payment_confirmations',
                'ordering': ['-submission_date'],
            },
        ),
    ]
