# Generated by Django 4.2.30 on 2026-09-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_adminnotification_order_payment_proof_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(help_text='Numeric Telegram User ID', max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('username', models.CharField(blank=True, default='', help_text='Telegram username without @', max_length=150)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin / Owner'), ('atelier_manager', 'Atelier Kitchen Manager'), ('logistics', 'Packaging & Delivery Staff'), ('admin', 'Store Admin')], default='admin', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is authorized to use the bot')),
                ('can_receive_alerts', models.BooleanField(default=True, help_text='Receive instant notifications for new orders')),
                ('can_manage_orders', models.BooleanField(default=True, help_text='Allowed to view and manage orders via bot')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Admin',
                'verbose_name_plural': 'Telegram Admins',
                'db_table': 'toomakt_telegram_admins',
                'ordering': ['-created_at'],
            },
        ),
    ]
